### ISSUE TITLE
Icon in QGIS not set properly

### ISSUE THREAD

**Issue by bgoesswe** [Open-EO/openeo-qgis-plugin#1]
The Icon shown in the toolbar is the default one and not the openEO icon.
![Screenshot_20190805_093414](https://user-images.githubusercontent.com/33025627/62447070-c3bbfb00-b764-11e9-9623-edcb30c4dad8.png)

**Comment by Nina-Gn** [comment]
In openeo_connector.py set: icon_path = './openeo-qgis-plugin-master/icon_new.png'
