### ISSUE TITLE
Set Temporal Extent in QGIS Plugin

### ISSUE THREAD

**Issue by Nina-Gn** [Open-EO/openeo-qgis-plugin#16]
List temporal extent option within the arguments?

"arguments": {
      "id": "S2B",
      "spatial_extent": null,
      "temporal_extent": null
    }

**Comment by Nina-Gn** [comment]
https://earthengine.openeo.org/v0.4/collections

**Comment by bgoesswe** [comment]
Collect temporal extent with calendar GUIs for the start and the end time. 
Ideally, the start time is set to the collections earliest available date. (Or the date range of the collection is visible somewhere.)
