### ISSUE TITLE
Integrate OpenEO-Hub into Plugin

### ISSUE THREAD

**Issue by bgoesswe** [Open-EO/openeo-qgis-plugin#17]
Get the available backends from the open-eo hub.
Let the user choose from them.
See: 
https://github.com/Open-EO/openeo-hub
https://github.com/Open-EO/openeo-web-editor/issues/25

**Comment by christophfriedrich** [comment]
Was this closed because it's now implemented? :)

**Comment by bgoesswe** [comment]
Yes, we automatically read the version >0.4.0 compliant backends from the openeo-hub API ;-)

**Comment by christophfriedrich** [comment]
Cool! :slightly_smiling_face: :+1:

Now I found where it is in your code.
What is this special handling for? Is it because the VITO entry is an object, not a string?

https://github.com/Open-EO/openeo-qgis-plugin/blob/dc6f860b9cbd285dc54fd67eb8b782ae339c3ff3/openeo_connector_dialog.py#L94

**Comment by bgoesswe** [comment]
Yes I am thought this will be maybe replaced when VITO implements this ".well-known"  URL, because I am not sure if this object can occur in general.

**Comment by bgoesswe** [comment]
Or is it some kind of standard that can also happen with other backends in the future ?

**Comment by christophfriedrich** [comment]
You're right, this will be replaced once VITO supports `.well-known` -- but it can occur in general.

A few days ago I added a [documentation paragraph to the Hub's README](https://github.com/Open-EO/openeo-hub#public-api-endpoints) that explains the format:

> links to .well-known documents where available, otherwise a link directly to the backend OR an object with several links to backends of the same provider

This construct is allowed in case there is a provider that has multiple backends but doesn't support `.well-known`. I think that's not too likely to occur again -- but it _may_ happen.

Another reason to change that `if` is that if the Hub's config would change (e.g. renaming "VITO GeoPySpark" to "VITO drivers") it wouldn't work anymore.

It would be better if that `if` would check *all* properties of the object for their type (`string` or `object`) and apply the special handling to all entries that were identified as objects.

**Comment by bgoesswe** [comment]
Yeah thats  true, we will fix this :)
