### ISSUE TITLE
Testing different backends with the qgis plugin

### ISSUE THREAD

**Issue by bgoesswe** [Open-EO/openeo-qgis-plugin#2]
- Testing all backends listed at the [validation tool](https://www.geo.tuwien.ac.at/openeoct) and the [openEO Hub](http://hub.openeo.org/). 
  -  Test Connection
  -  Check loaded collections and processes
  -  Check existing jobs and execution/display functionality
  -  Test sending example process graphs to the backends to create jobs.

**Comment by bgoesswe** [comment]
If an Error occurs, add exception handling and provide the user with a useful notification.

**Comment by Nina-Gn** [comment]
backend name | backend URL | backend listed in | 1 – Test Connection(im QGIS Plugin) |   | 2 – Check loaded Collections and processes
-- | -- | -- | -- | -- | --
VITO GeoPySpark 0.3 | http://openeo.vgt.vito.be/openeo/ | OpeneoCT | X | Python error: An error has occurred while executing Python code: See message log (Python Error) for more details. | ?
VITO GeoPySpark 0.4 | http://openeo.vgt.vito.be/openeo/0.4.0 | OpeneoCT | X | Python error: An error has occurred while executing Python code: See message log (Python Error) for more details. | ?
  |   |   |   |   |  
Google Earth Engine v0.3.1 | http://earthengine.openeo.org/v0.3 | OpenEO Hub | ✓ | Success | -
Google Earth Engine 0.4 | https://earthengine.openeo.org/v0.4 | OpeneoCT | ✓ | Success | No Job Collection yet
  |   |   |   |   |  
v0.3.0 | http://openeo.mundialis.de/api/v0.3 | OpenEO Hub | ✓ | Success | No Job Collection yet
mundialis GRASS GIS 0.4 | https://openeo.mundialis.de/api/v0.4 | OpeneoCT | ✓ | Authentication failed | ?
  |   |   |   |   |  
EODC v0.4 | https://openeo.eodc.eu | OpeneoCT | X | Terminates QGIS | ?
Eurac Research – openEO-backend v0.4.2 | https://openeo.eurac.edu/ | OpenEO Hub | ✓ | Success | No Job Collection yet
  |   |   |   |   |  
v0.3.1 | http://saocompute.eurac.edu/openEO_0_3_0/openeo | OpenEO Hub | ✓ | Success | No Job Collection yet
R Demo Server v0.3.1 | https://r-server.openeo.org | OpenEO Hub | ✓ | Success | No Job Collection yet
  |   |   |   |   |  
Google Earth Engine Proxy for OpenEO | gleiche URL wie Google Earth Engine 0.4 | OpenEO Hub | ✓ | Success | -
GRASS GIS Driver v0.4.0 | gleiche URL wie mundialis GRASS GIS 0.4 | OpenEO Hub | ✓ | Success | -
OpenEO API v0.4.0 | gleiche URL wie VITO GeoPySpark 0.4 | OpenEO Hub | X | Python error: An error has occurred while executing Python code: See message log (Python Error) for more details. | -
mundialis GRASS GIS (Actina) v0.3.1 | gleiche URL wie v0.3.1 | OpenEO Hub | ✓ | Success | -
OpenEO API v0.3.1 | gleiche URL wie VITO GeoPySpark 0.3 | OpenEO Hub | X | Version in URL missing? Python error: An error has occurred while executing Python code: See message log (Python Error) for more details. | -

**Comment by Nina-Gn** [comment]
[Issue2_CheckBackends.xlsx](https://github.com/Open-EO/openeo-qgis-plugin/files/3520529/Issue2_CheckBackends.xlsx)
