### ISSUE TITLE
Connection to Hub Exchange (Process Graph)

### ISSUE THREAD

**Issue by bgoesswe** [Open-EO/openeo-qgis-plugin#49]
Add the possibility to load the process graphs from the openeo hub (hub.openeo.org)

Like loading the process graph and maybe exchanging the extent accordingly to the selection.

The endpoint is described here:
/process_graphs at:
https://github.com/Open-EO/openeo-hub

**Comment by Nina-Gn** [comment]
http://hub.openeo.org/api/process_graphs

**Comment by Nina-Gn** [comment]
All process graphs can be loaded and most of them executed.

Limit the displayed process graphs to those, which can really be executed. E.g. try to create the second last job of the list in GEE. Not possible!

**Comment by bgoesswe** [comment]
I think that's good enough for now, I'll close this issue
