### ISSUE TITLE
Maybe some kind of Wizard

### ISSUE THREAD

**Issue by bgoesswe** [Open-EO/openeo-qgis-plugin#54]
Maybe it would be good to have some kind of "create Job" Wizard, which guides the user through the process of creating a job. 

So that fist he can log in then press "Next" and then he chooses a collection, then spatial extent then temporal extent and then bands, after that he can choose to use the selection in a process graph from the Hub or just create a load_collection process... 

That is because I feel like the user is a little bit overwhelmed by the options when starting the plugin. So a new user starts the plugin and sees a lot of empty comboboxes and text fields and does not quite know, in what order he should execute things...

**Comment by Nina-Gn** [comment]
related to #58
