### ISSUE TITLE
Don't require users to choose an API version

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-qgis-plugin#66]
Well-known discovery was added to the API so that users by default don't have to choose an API version, which they usually doesn't know anything about. Therefore the API docs says:

> By default, a client SHOULD connect to the most recent production-ready version it supports. The most recent version is determined by comparing the version numbers according to rules from Semantic Versioning, especially §11. Clients MAY let users choose to connect to versions that are not production-ready versions or outdated.

So instead of just allowing to connect to https://earthengine.openeo.org/v1.0 it should also allow to pass https://earthengine.openeo.org and then the client chooses the most recent production-ready version supported by the client from well-known discovery. I guess that's what users want to use in most cases anyway. 

Could probably be related https://github.com/Open-EO/openeo-python-client/issues/142 if QGIS uses the Python lib.

**Comment by bgoesswe** [comment]
That is implemented, the user can either put a concrete version of the backend or the base url (which then chooses the latest compatible version). By default, it provides a drop-down menu with all backends listed at the openEO Hub.
