### ISSUE TITLE
No versions for Wekeo CREODIAS or VITO

### ISSUE THREAD

**Issue by raphaeljolivet** [Open-EO/openeo-qgis-plugin#77]
Hi, I was trying the OpenEO plugin and wanted to log to Wekeo, but it fails with a stack trace : 

```
 File "/home/rjolivet/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/openeo-qgis-plugin-master/models/openeohub.py", line 26, in get_latest_version
    return self.version_urls[latest_ver]
KeyError: '0.0.0'
```

Looking deeper and adding some traces, I found that the URLs setup for some providers are not working at all (no payload returned) : 

- VITO https://openeo.vito.be/
- WEkEO https://openeo.wekeo.eu/
- CREODIAS https://openeo.creo.vito.be/

As a result, none of them are working.
Who is responsible for the maintenance of those services ?

**Comment by m-mohr** [comment]
Sorry for the slow reply. Currently, there is the unfortunate situation that there is no maintainer for this plugin.

The clients usually append `/.well-known/openeo` to the URLs. The result is the well-known URI, which contains all information to choose the right version and URL of the back-end to connect to. For VITO that is https://openeo.vito.be/.well-known/openeo

What you could try is to use the URLs you find in those documents, e.g. https://openeo.vito.be/openeo/1.0/ for the 1.0 version of the VITO back-end. Wekeo seems to be offline though.

The underlying issue with the plugin seems to be that without authentication it still requests jobs, which the back-ends probably returns in a non-compliant way. We are open to accept and merge PRs, but we haven't got anyone at hand who can fix the issue right now.

**Comment by lforesta** [comment]
Hi, unfortunately the WEkEO back-end at that URL is currently not maintained. Also, it only exposed one collection (S3 OLCI) of all the datasets offered by WEkEO.

**Comment by raphaeljolivet** [comment]
Ok, thanks for this answer. 
I will do things manually I guess.

**Comment by lforesta** [comment]
@raphaeljolivet may I ask what do you want to do and on which back-end?

**Comment by lmenard** [comment]
> @raphaeljolivet may I ask what do you want to do and on which back-end?

Hi, I reply to your request while browsing this email thread. The QGIS frontend with OpenEO support would enable to trigger remote OGC WPS deployed on WEkEO, to access, process and retrieve high resolution solar radiation data including variability in space and time in support to PV penetration at urban scale scenario. This pilot is developed in the framework of the Horizon 2020 funded project e-shape. More information here: https://e-shape.eu/index.php/showcases/pilot3-2-high-photovoltaic-penetration-at-urban-scale
Best regards,
Lionel

**Comment by m-mohr** [comment]
@sophieherrmann

**Comment by sophieherrmann** [comment]
I'm sorry to say, but the WEkEO backend is still not actively maintained and this is also not planed for the near future. If this changes, I'm happy to announce this here.

**Comment by lmenard** [comment]
> I'm sorry to say, but the WEkEO backend is still not actively maintained and this is also not planed for the near future. If this changes, I'm happy to announce this here.

Hi Sophie, thanks for the information on the current status of WEkEO implementation of Open-EO. Please share any new inputs here. Thanks in advance. Lionel
