### ISSUE TITLE
Connector python error

### ISSUE THREAD

**Issue by iLux24** [Open-EO/openeo-qgis-plugin#81]
Hello, 
I've just installed QGis and OpenEO plugin. I'm facing some issues while trying to connect to the backend. I'm trying to access to Sentinel Hub(with valid credentials) and it's giving me this error:
![qgiserror](https://github.com/Open-EO/openeo-qgis-plugin/assets/62053696/f7758188-ac29-4e3a-b00e-1f910a3d285a)

For testing reasons I've tried to connect to Copernicus data space ecosystem (using the URL https://openeo.dataspace.copernicus.eu/openeo/1.2), and using valid credentials I've faced the "Authentication Failed" error. 
![qgiserror](https://github.com/Open-EO/openeo-qgis-plugin/assets/62053696/ebf38e5d-1ce7-4094-b273-16ceb3d47612)

**Comment by raphaeljolivet** [comment]
Same here.
Is this plugin still supported ?

**Comment by m-mohr** [comment]
No, it's currently unsupported, sorry.
